// <auto-generated />
using ByteCuisine.Server.Controllers.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ByteCuisine.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240111235914_Test")]
    partial class Test
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ByteCuisine.Shared.Account", b =>
                {
                    b.Property<int>("User_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("User_Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PictureData")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("User_Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("ByteCuisine.Shared.Dish", b =>
                {
                    b.Property<int>("Dish_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Dish_Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("DishImage")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Dish_Id");

                    b.ToTable("Dishes");
                });

            modelBuilder.Entity("ByteCuisine.Shared.DishIngredient", b =>
                {
                    b.Property<int>("DishIngredient_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DishIngredient_Id"));

                    b.Property<int>("Dish_Id")
                        .HasColumnType("int");

                    b.Property<int>("Ingredient_Id")
                        .HasColumnType("int");

                    b.HasKey("DishIngredient_Id");

                    b.HasIndex("Dish_Id");

                    b.HasIndex("Ingredient_Id");

                    b.ToTable("DishIngredients");
                });

            modelBuilder.Entity("ByteCuisine.Shared.Ingredient", b =>
                {
                    b.Property<int>("Ingredient_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Ingredient_Id"));

                    b.Property<double>("Callories")
                        .HasColumnType("float");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Ingredient_Id");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("ByteCuisine.Shared.IngredientsInFridge", b =>
                {
                    b.Property<int>("IngredientsInFridge_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IngredientsInFridge_Id"));

                    b.Property<int>("Ingredient_Id")
                        .HasColumnType("int");

                    b.Property<int>("VirtualFridge_Id")
                        .HasColumnType("int");

                    b.HasKey("IngredientsInFridge_Id");

                    b.HasIndex("Ingredient_Id");

                    b.HasIndex("VirtualFridge_Id");

                    b.ToTable("IngredientsInFridges");
                });

            modelBuilder.Entity("ByteCuisine.Shared.Theme", b =>
                {
                    b.Property<int>("Theme_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Theme_Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("ThemeImage")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Theme_Id");

                    b.ToTable("Themes");
                });

            modelBuilder.Entity("ByteCuisine.Shared.VirtualFridge", b =>
                {
                    b.Property<int>("VirtualFridge_Id")
                        .HasColumnType("int");

                    b.Property<int>("Theme_Id")
                        .HasColumnType("int");

                    b.HasKey("VirtualFridge_Id");

                    b.HasIndex("Theme_Id");

                    b.ToTable("VirtualFridges");
                });

            modelBuilder.Entity("ByteCuisine.Shared.DishIngredient", b =>
                {
                    b.HasOne("ByteCuisine.Shared.Dish", "Dish")
                        .WithMany("DishIngredients")
                        .HasForeignKey("Dish_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ByteCuisine.Shared.Ingredient", "Ingredient")
                        .WithMany("DishIngredients")
                        .HasForeignKey("Ingredient_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dish");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("ByteCuisine.Shared.IngredientsInFridge", b =>
                {
                    b.HasOne("ByteCuisine.Shared.Ingredient", "Ingredient")
                        .WithMany("IngredientsInFridge")
                        .HasForeignKey("Ingredient_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ByteCuisine.Shared.VirtualFridge", "VirtualFridge")
                        .WithMany("IngredientsInFridge")
                        .HasForeignKey("VirtualFridge_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("VirtualFridge");
                });

            modelBuilder.Entity("ByteCuisine.Shared.VirtualFridge", b =>
                {
                    b.HasOne("ByteCuisine.Shared.Theme", "Theme")
                        .WithMany("VirtualFridges")
                        .HasForeignKey("Theme_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ByteCuisine.Shared.Account", "Account")
                        .WithOne("VirtualFridge")
                        .HasForeignKey("ByteCuisine.Shared.VirtualFridge", "VirtualFridge_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Theme");
                });

            modelBuilder.Entity("ByteCuisine.Shared.Account", b =>
                {
                    b.Navigation("VirtualFridge")
                        .IsRequired();
                });

            modelBuilder.Entity("ByteCuisine.Shared.Dish", b =>
                {
                    b.Navigation("DishIngredients");
                });

            modelBuilder.Entity("ByteCuisine.Shared.Ingredient", b =>
                {
                    b.Navigation("DishIngredients");

                    b.Navigation("IngredientsInFridge");
                });

            modelBuilder.Entity("ByteCuisine.Shared.Theme", b =>
                {
                    b.Navigation("VirtualFridges");
                });

            modelBuilder.Entity("ByteCuisine.Shared.VirtualFridge", b =>
                {
                    b.Navigation("IngredientsInFridge");
                });
#pragma warning restore 612, 618
        }
    }
}
